DROP SCHEMA IF EXISTS `cakestore` ;
CREATE SCHEMA IF NOT EXISTS `cakestore`;


CREATE TABLE IF NOT EXISTS `cakestore`.`cake` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(40) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `rating` FLOAT NULL DEFAULT NULL,
  `image` VARCHAR(200) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1